### ISSUE TITLE
turbograft + turbolinks gem gets a stack to deep exception

### ISSUE THREAD

**Issue by celsodantas** [Shopify/turbograft#42]
This is what happen when you have: 
```
gem 'turbolinks'
gem 'turbograft'
```

And  you access a page in the app (don't need to include anything in the application.js):
```
SystemStackError (stack level too deep):
  actionpack (4.1.4) lib/action_dispatch/middleware/reloader.rb:79


  Rendered /Users/celsodantas/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (0.6ms)
  Rendered /Users/celsodantas/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.0ms)
  Rendered /Users/celsodantas/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /Users/celsodantas/.rvm/gems/ruby-2.1.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (13.9ms)
```

@qq99 @nsimmons 
not urgent but would be cool to investigate.

**Comment by mkhairi** [comment]
i have the similar issue, i guess it incompatible with gem 'simple-navigation' renderer.

**Comment by Nielsomat** [comment]
This is actually due to both turbograft & turbolink alias_method_chain-ing url_for but using the same name: see https://github.com/Shopify/turbograft/blob/master/lib/turbograft/xhr_url_for.rb#L12 and https://github.com/rails/turbolinks/blob/master/lib/turbolinks/xhr_url_for.rb#L20. This leads to calls being bounced back and forth between the two implementations endlessly, and the stack thus overflowing.

As turbograft is a fork of turbolinks, you can't use the two together. Choose one or the other.

**Comment by pushrax** [comment]
As mentioned, turbograft and turbolinks are fundamentally incompatible, I don't think there is any need to support the combination.

**Comment by abolishme** [comment]
i had a similar problem with `gem 'turbolinks-redirect'`.
