### ISSUE TITLE
Tubolinks 3 Migration Strategy

### ISSUE THREAD

**Issue by mikeantonelli** [Shopify/turbograft#95]
Hi, I was wondering if you all would be willing to share your thoughts on migration to Turbolinks 3, once it's released?

Mainly, is there a desire to maintain the fork given that the upcoming release cites partial page refreshes as a primary feature?

Any info would be greatly appreciated, thank you.

**Comment by patrickdonovan** [comment]
Realistically the answer is "it depends". It would be nice to be able to just migrate to Turbolinks 3 if that's possible, and if it's not too drastic of an effort. But right now turbograft is working quite well for us and whether Turbolinks 3 will meet all our needs when released is somewhat unclear.

**Comment by TheMallen** [comment]
We might want to move to TL5 since it has some cool cacheing behaviour and a very nice architecture, though I think the effort involved would be immense (it does not support partial replaces at all), and their head asset tracking solution is a little weird (if you want to refresh when an asset is updated then you are also locked into a refresh when a tracked asset is not present, which would cause refreshes in Shopify when navigating from any non-home page to home, whereae `Turbohead` only refreshes when there is a conflict or when moving to a page with no tracked assets at all). 

That being said, I don't think this is the right place to discuss that (should be inside of `Shopify/Shopify` or on slack. I'm closing this for now as part of trying to make the TG issue tracker more manageable.
